### ISSUE TITLE
Minor misspelling

### ISSUE THREAD

**Issue by romanus** [jhu-ep-coursera/fullstack-course5#22]
Hi @ychaikin!  I'm watching your AngularJS Coursera course, and I wanna say it's really awesome! Thank you!

Now down to business. In lectures 51-70 in `src/public/public.routes.js` you set state property `absract` instead of `abstract`. It doesn't crash the program because you don't try to switch over this state, but now you can achieve it.

Hope you fix it in future commits! Thank you million times for this great course!

**Comment by ZKjellberg** [comment]
Shouldn't this issue be closed now as commits were made to resolve the issue?
