### ISSUE TITLE
Lectures 55+ Samples are currently broken due to Heroku instance error

### ISSUE THREAD

**Issue by ZKjellberg** [jhu-ep-coursera/fullstack-course5#47]
When testing the example code for **Lectures55 and above**, I receive an error when I attempt to invoke **Menu** or **Specials** as they produce the errors below:

```
GET https://ychaikin-course5.herokuapp.com/categories.json 503 (Service Unavailable)
Failed to load https://ychaikin-course5.herokuapp.com/categories.json: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 503.
```

The URL https://ychaikin-course5.herokuapp.com/categories.json provides an *Application error** when accessed directly, so it appears this Heroku instance is not working correctly.

If I modify [common.module.js](https://github.com/jhu-ep-coursera/fullstack-course5/blob/master/examples/Lecture55/src/common/common.module.js), and change the URL to match the URL used in previous assignments to **https://davids-restaurant.herokuapp.com**, I can successfully test the code.

For a near-term solution, I can change this file for all examples for Example 55+. For the course, I suspect the best solution would be to update the original Heroku instance, unless there were plans to migrate.

**Comment by ychaikin** [comment]
@ZKjellberg In the instructions or the video (can't remember which, maybe both), it's explained that ychaikin-course5 deployment of the backend is only there for the video and is not deployed for the class.

Instead, the instructions tell you to deployed *your own* deployment of the backend and gives you instructions on how to do that.

All the best,
-Yaakov.
